language: python
python:
  - "3.8"
install:
  - pip install coveralls
script:
  - python -m unittest mymodule.py
  - coverage run
after_success: coveralls
notifications:
  email:
    recipients:
      - joseguzman@upeu.edu.pe
    on_success: always
    on_failure: always